import {lazy} from "react";

export const ErrorPage = lazy(() => import("../pages/404.jsx"))
export const DashBoardPage = lazy(() => import("../pages/admin/Dashboard.jsx"))
export const UserListPage = lazy(() => import("../pages/admin/users/UserList.jsx"))
export const UserFormPage = lazy(() => import("../pages/admin/users/UserForm.jsx"))
export const CoachCarListPage = lazy(() => import("../pages/admin/coaches/CoachList.jsx"))
export const CoachCarFormPage = lazy(() => import("../pages/admin/coaches/CoachForm.jsx"))
export const AdminSignInPage = lazy(() => import("../pages/admin/auth/SignIn.jsx"))
export const AdminHomePage = lazy(() => import("../layouts/admin/AdminMainLayout.jsx"))
export const BookingListPage = lazy(() => import("../pages/admin/BookingList.jsx"))
export const RevenuePage = lazy(() => import("../pages/admin/Revenue.jsx"))
export const NewsListPage = lazy(() => import("../pages/admin/news/NewsList.jsx"))
export const TestimonialListPage = lazy(() => import("../pages/admin/testimonials/TestimonialList.jsx"))
export const TestimonialFormPage = lazy(() => import("../pages/admin/testimonials/TestimonialForm.jsx"))
export const UtilityListPage = lazy(() => import("../pages/admin/utilities/UtilityList.jsx"))
export const UtilityFormPage = lazy(() => import("../pages/admin/utilities/UtilityForm.jsx"))
export const ScheduleListPage = lazy(() => import("../pages/admin/schedules/ScheduleList.jsx"))
export const ScheduleFormPage = lazy(() => import("../pages/admin/schedules/ScheduleForm.jsx"))
export const PriceTicketListPage = lazy(() => import("../pages/admin/priceTicket/PriceTicketList.jsx"))
export const PriceTicketFormPage = lazy(() => import("../pages/admin/priceTicket/PriceTicketForm.jsx"))
export const PolicyListPage = lazy(() => import("../pages/admin/policies/PolicyList.jsx"))
export const CustomerMainLayout = lazy(() => import("../layouts/customer/MainLayout.jsx"))
export const CustomerHomePage = lazy(() => import("../pages/customer/home/CustomerHomePage.jsx"))
export const ResetPasswordPage = lazy(() => import("../pages/ResetPassword.jsx"))
export const ContactListPage = lazy(() => import("../pages/admin/contact/ContactList.jsx"))
export const LocationListPage = lazy(() => import("../pages/admin/locations/LocationList.jsx"))
export const LocationFormPage = lazy(() => import("../pages/admin/locations/LocationForm.jsx"))
export const BookingCoachPage = lazy(() => import("../pages/customer/bookingCoach/BookingCoach.jsx"))
export const BookingSeatPage = lazy(() => import("../pages/customer/bookingSeat/BookingSeat.jsx"))
export const CustomerProfilePage = lazy(() => import("../pages/customer/profile/Profile.jsx"))
export const PaymentPage = lazy(() => import("../pages/customer/Payment.jsx"))
export const CalendarPage = lazy(() => import("../pages/admin/calendar/CalendarPage.jsx"))
export const DivisionPage = lazy(() => import("../pages/admin/division/DivisionPage.jsx"))

export const DivisionDetailPage = lazy(() => import("../pages/admin/division/DivisionDetail.jsx"))

export const ContactPage = lazy(() => import("../pages/customer/Contact.jsx"))

export const AdminProfilePage = lazy(() => import("../pages/admin/Profile.jsx"))

export const DistanceListPage = lazy(() => import("../pages/admin/distance/DistanceList.jsx"))

export const DistanceFormPage = lazy(() => import("../pages/admin/distance/DistanceForm.jsx"))